// backend/services/alertEngine.js
const ALERT_RULES  = require('../config/alertRules');
const Alert        = require('../models/Alert');
const Incident     = require('../models/Incident');
const { isOnCooldown, markFired } = require('./alertCooldown');
const { sendSlackNotification }   = require('./notificationService');
const { sendEmailNotification }   = require('./notificationService');

let _io = null;

const setIO = (io) => { _io = io; };

// ── Main entry point ──────────────────────────
// Called from metricsQueue after every flush
const evaluateMetrics = async (metrics) => {
  for (const metric of metrics) {
    for (const rule of ALERT_RULES) {
      const value = metric[rule.field];
      if (value === undefined) continue;

      if (value >= rule.threshold) {
        await handleBreach(metric, rule, value);
      }
    }
  }
};

// ── Handle a single threshold breach ─────────
const handleBreach = async (metric, rule, value) => {
  const { host } = metric;

  // Skip if still in cooldown window
  if (isOnCooldown(rule.id, host)) return;

  // Mark fired immediately to prevent race conditions
  markFired(rule.id, host);

  try {
    // 1. Create alert document
    const alert = await Alert.create({
      host,
      metricType:     rule.metricType,
      threshold:      rule.threshold,
      triggeredValue: value,
      severity:       rule.severity,
      status:         'active',
    });

    // 2. Auto-create incident for critical/high
    let incident = null;
    if (rule.severity === 'critical' || rule.severity === 'high') {
      incident = await Incident.create({
        title:       rule.message(host, value),
        description: `Auto-generated by alert engine. Rule: ${rule.id}`,
        severity:    rule.severity,
        host,
        timeline: [{
          note: `Auto-created by alert engine — ${rule.metricType} at ${value.toFixed(1)}% (threshold: ${rule.threshold}%)`,
        }],
      });

      // Link incident to alert
      alert.incident = incident._id;
      await alert.save();
    }

    // 3. Send notifications
    const message = rule.message(host, value);
    await Promise.allSettled([
      sendSlackNotification({ alert, incident, message, rule }),
      sendEmailNotification({ alert, incident, message, rule }),
    ]);

    // 4. Broadcast to dashboard
    if (_io) {
      _io.emit('alert:fired', { alert, incident });
    }

    console.log(`[AlertEngine] ${rule.severity.toUpperCase()} — ${message}`);
  } catch (err) {
    console.error('[AlertEngine] Error handling breach:', err.message);
  }
};

module.exports = { evaluateMetrics, setIO };