// frontend/src/pages/alerts/AlertList.jsx
import useAlerts      from '../../hooks/useAlerts';
import AlertRow       from '../../components/alerts/AlertRow';
import AlertFilters   from '../../components/alerts/AlertFilters';
import Spinner        from '../../components/ui/Spinner';

export default function AlertList() {
  const {
    alerts, stats, loading,
    filters, pagination,
    updateFilter, acknowledge, resolve,
  } = useAlerts();

  return (
    <div className="flex-1 overflow-y-auto p-6">

      {/* Stats strip */}
      {stats && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
          <StatCard label="Total"        value={stats.total}                       color="text-indigo-400" />
          <StatCard label="Active"       value={stats.byStatus?.active       || 0} color="text-red-400"    />
          <StatCard label="Acknowledged" value={stats.byStatus?.acknowledged  || 0} color="text-yellow-400" />
          <StatCard label="Resolved"     value={stats.byStatus?.resolved     || 0} color="text-green-400"  />
        </div>
      )}

      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
        <div>
          <h1 className="text-white text-2xl font-bold">Alerts</h1>
          <p className="text-slate-500 text-sm mt-0.5">
            {pagination.total} total alerts · auto-generated by alert engine
          </p>
        </div>

        {/* Live indicator */}
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          <span className="text-slate-500 text-xs">Live via Socket.IO</span>
        </div>
      </div>

      {/* Filters */}
      <div className="mb-4">
        <AlertFilters filters={filters} onFilter={updateFilter} />
      </div>

      {/* Table */}
      <div className="bg-[#0a0e1a] border border-indigo-900/40 rounded-2xl overflow-hidden">
        {loading ? (
          <div className="flex justify-center py-16">
            <Spinner />
          </div>
        ) : alerts.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 gap-3">
            <p className="text-slate-500 text-sm">No alerts yet</p>
            <p className="text-slate-600 text-xs">
              Alerts fire automatically when metrics cross thresholds
            </p>
          </div>
        ) : (
          <table className="w-full">
            <thead>
              <tr className="border-b border-indigo-900/40 text-left">
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Alert</th>
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Severity</th>
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Status</th>
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Incident</th>
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Age</th>
                <th className="px-4 py-3 text-slate-400 text-xs font-medium uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody>
              {alerts.map((alert) => (
                <AlertRow
                  key={alert._id}
                  alert={alert}
                  onAcknowledge={acknowledge}
                  onResolve={resolve}
                />
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Pagination */}
      {pagination.pages > 1 && (
        <div className="flex items-center justify-center gap-3 mt-4">
          <button
            disabled={filters.page <= 1}
            onClick={() => updateFilter('page', filters.page - 1)}
            className="px-3 py-1.5 text-sm text-slate-400 border border-indigo-900/60 rounded-lg hover:border-indigo-500 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            ← Prev
          </button>
          <span className="text-slate-500 text-sm">
            Page {filters.page} of {pagination.pages}
          </span>
          <button
            disabled={filters.page >= pagination.pages}
            onClick={() => updateFilter('page', filters.page + 1)}
            className="px-3 py-1.5 text-sm text-slate-400 border border-indigo-900/60 rounded-lg hover:border-indigo-500 disabled:opacity-30 disabled:cursor-not-allowed"
          >
            Next →
          </button>
        </div>
      )}
    </div>
  );
}

function StatCard({ label, value, color }) {
  return (
    <div className="bg-[#0a0e1a] border border-indigo-900/40 rounded-xl px-4 py-3">
      <p className="text-slate-500 text-xs mb-1">{label}</p>
      <p className={`text-2xl font-bold ${color}`}>{value}</p>
    </div>
  );
}